[package]
name = "kakkoapp"
version = "0.1.0"
authors = ["Yuki Yamaura <ymruki@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
plotters = "0.3.5"
wasm-bindgen = "0.2.87"

[profile.release]
lto = true
